export { NavBar } from "./NavBar";
export { Main } from "./Main";
export { SectionNextDecision } from "./SectionNextDecision";
export { SectionMultiply } from "./SectionMultiply";
export { SectionAuthor } from "./SectionAuthor";
export { SectionStatistic } from "./SectionStatistic";
export { SectionSubscribe } from "./SectionSubscribe";
export { SectionLogin } from "./SectionLogin";
export { Footer } from "./Footer";
